version: '3.7'


services:
  # Cypress test results as Prometheus metrics
  cypress-prom-metrics:
    build:
      context: .

    image: alexeytsarev/cypress-prom-metrics:1.0.0
    container_name: cypress-prom-metrics
    restart: on-failure

    environment:
      - TERM=xterm
      - DELAY_TIMEOUT=0
      - ITER_LIMIT=1
      - CYPRESS_BASE_URL=http://nginx-stable
      - PUSH_GATEWAY_URL=http://push-gateway:9091
      - PUSH_GATEWAY_JOB_NAME=test:test
      - METRICS_DEFAULT_LABEL_NAME=origin
      - METRICS_DEFAULT_LABEL_VALUE=me:me
#      - CYPRESS_TEST_NAME=home_page

    labels:
      - SERVICE_NAME=cypress-prom-metrics

    logging:
      driver: journald
      options:
        tag: cypress-prom-metrics

    ports:
      - "8080:8080"
  # End Cypress test results as Prometheus metrics


  # Nginx stable
  nginx-stable:
    image: nginx:stable
    container_name: nginx-stable
    restart: unless-stopped

    environment:
      - TERM=xterm

    labels:
      - SERVICE_NAME=nginx-stable

    logging:
      driver: journald
      options:
        tag: nginx-stable

    ports:
      - "80:80"
  # End Nginx stable


  # Prometheus PushGateway
  push-gateway:
    image: prom/pushgateway
    container_name: push-gateway
    restart: unless-stopped

    environment:
      - TERM=xterm

    labels:
      - SERVICE_NAME=push-gateway

    logging:
      driver: journald
      options:
        tag: push-gateway

    ports:
      - "9091:9091"
  # End Prometheus PushGateway


  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

    environment:
      - TERM=xterm

    labels:
      - SERVICE_NAME=prometheus

    logging:
      driver: journald
      options:
        tag: prometheus

    ports:
      - "9090:9090"
    # End Prometheus
