global:
  scrape_interval: 5s
  scrape_timeout: 2s
  evaluation_interval: 15s

scrape_configs:
  - job_name: test:test1
    honor_labels: true
    static_configs:
      - targets:
          - 'push-gateway:9091'
    metric_relabel_configs:
#      - source_labels: [origin]
#        regex: 'me:me'
#        action: keep
      - source_labels: [job]
        regex: 'test:test0'
        action: keep
